---
title: "Q1_simple"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#igraph package
#install.packages("igraph")
library(igraph)
```

## Simple network graphs for Q1 VAST Challenge 2020 MC1


```{r echo=FALSE}
# change directory to the data
setwd("E:\\OVGU\\WiSe19_20\\VA project\\VAST2020\\MC1\\MC1\\data")
```

## Graphs

Graph for CGCS-Template.csv file:

```{r echo=TRUE}

# load the CGCS-Template.csv file
CGCS_Template <- read.csv("CGCS-Template.csv")


# Filtering only Source, Target and eType
CGCS_Template_01 <- CGCS_Template[c(c(1,3),2)]


# Creating a graph data structure
template_01_graph <- graph.data.frame(
  d = CGCS_Template_01,
  directed = FALSE
)


# Creating graph clusters
clusters_template_01 <- cluster_edge_betweenness(template_01_graph)

# Plot a cluster graph
plot(
  x = clusters_template_01,
  y = template_01_graph,
  vertex.size = 3,
  vertex.label = NA,
  edge.curved = FALSE,
  main = "Adjusted cluster template graph of only Source, Target and eType"
)


```

Graph for Q1-Graph1.csv file:


```{r echo=FALSE}
# Load the Q1-Graph1.csv file
Q1_graph01 <- read.csv("Q1-Graph1.csv")


# Filtering only Source, Target and eType
Q1_graph01_filtered <- Q1_graph01[c(c(1,3),2)]


# Creating a graph data structure
Q1_graph01_filtered_graph <- graph.data.frame(
  d = Q1_graph01_filtered,
  directed = FALSE
)

# Creating graph clusters
clusters_Q1_graph01_filtered_graph <- cluster_edge_betweenness(Q1_graph01_filtered_graph)

# Plot a cluster graph
plot(
  x = clusters_Q1_graph01_filtered_graph,
  y = Q1_graph01_filtered_graph,
  vertex.size = 3,
  vertex.label = NA,
  edge.curved = FALSE,
  main = "Adjusted cluster Q1-Graph1 graph of only Source, Target and eType"
)
```


Graph for Q1-Graph2.csv file:


```{r echo=FALSE}
# Load the Q1-Graph2.csv file
Q1_graph02 <- read.csv("Q1-Graph2.csv")


# Filtering only Source, Target and eType
Q1_graph02_filtered <- Q1_graph02[c(c(1,3),2)]


# Creating a graph data structure
Q1_graph02_filtered_graph <- graph.data.frame(
  d = Q1_graph02_filtered,
  directed = FALSE
)

# Creating graph clusters
clusters_Q1_graph02_filtered_graph <- cluster_edge_betweenness(Q1_graph02_filtered_graph)

# Plot a cluster graph
plot(
  x = clusters_Q1_graph02_filtered_graph,
  y = Q1_graph02_filtered_graph,
  vertex.size = 3,
  vertex.label = NA,
  edge.curved = FALSE,
  main = "Adjusted cluster Q1-Graph2 graph of only Source, Target and eType"
)
```

Graph for Q1-Graph3.csv file:


```{r echo=FALSE}
# Load the Q1-Graph3.csv file
Q1_graph03 <- read.csv("Q1-Graph3.csv")


# Filtering only Source, Target and eType
Q1_graph03_filtered <- Q1_graph03[c(c(1,3),2)]


# Creating a graph data structure
Q1_graph03_filtered_graph <- graph.data.frame(
  d = Q1_graph03_filtered,
  directed = FALSE
)

# Creating graph clusters
clusters_Q1_graph03_filtered_graph <- cluster_edge_betweenness(Q1_graph03_filtered_graph)

# Plot a cluster graph
plot(
  x = clusters_Q1_graph03_filtered_graph,
  y = Q1_graph03_filtered_graph,
  vertex.size = 3,
  vertex.label = NA,
  edge.curved = FALSE,
  main = "Adjusted cluster Q1-Graph3 graph of only Source, Target and eType"
)
```




Graph for Q1-Graph4.csv file:


```{r echo=FALSE}
# Load the Q1-Graph4.csv file
Q1_graph04 <- read.csv("Q1-Graph4.csv")


# Filtering only Source, Target and eType
Q1_graph04_filtered <- Q1_graph04[c(c(1,3),2)]


# Creating a graph data structure
Q1_graph04_filtered_graph <- graph.data.frame(
  d = Q1_graph04_filtered,
  directed = FALSE
)

# Creating graph clusters
clusters_Q1_graph04_filtered_graph <- cluster_edge_betweenness(Q1_graph04_filtered_graph)

# Plot a cluster graph
plot(
  x = clusters_Q1_graph04_filtered_graph,
  y = Q1_graph04_filtered_graph,
  vertex.size = 3,
  vertex.label = NA,
  edge.curved = FALSE,
  main = "Adjusted cluster Q1-Graph4 graph of only Source, Target and eType"
)
```


Graph for Q1-Graph5.csv file:



```{r echo=FALSE}
# Load the Q1-Graph5.csv file
Q1_graph05 <- read.csv("Q1-Graph5.csv")


# Filtering only Source, Target and eType
Q1_graph05_filtered <- Q1_graph05[c(c(1,3),2)]


# Creating a graph data structure
Q1_graph05_filtered_graph <- graph.data.frame(
  d = Q1_graph05_filtered,
  directed = FALSE
)

# Creating graph clusters
clusters_Q1_graph05_filtered_graph <- cluster_edge_betweenness(Q1_graph05_filtered_graph)

# Plot a cluster graph
plot(
  x = clusters_Q1_graph05_filtered_graph,
  y = Q1_graph05_filtered_graph,
  vertex.size = 3,
  vertex.label = NA,
  edge.curved = FALSE,
  main = "Adjusted cluster Q1-Graph5 graph of only Source, Target and eType"
)
```