---
title: "BigData-Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(plyr)
```

## Procurement Channel:

```{r cars}
# Load The Data:
bg23 <- data.table::fread(here::here("data", "BigGraphData", "procurement.csv"))

nrow(bg23)

head(bg23)
length(unique(bg23$Target))
length(unique(bg23$Source))

```



```{r}
#unique(bg23$Source) 
#unique(bg23$Target)

#bg23[bg23$Target==641131 & bg23$eType == 2]

#bg23$Time[bg23$Target==641131]

bg2 <- bg23 %>% filter(bg23$eType==2)
bg3 <- bg23 %>% filter(bg23$eType==3)

```

```{r}
items_sold <- count(bg2, c("Source","Target")) # Trying to find interesting items which were sold multiple times.
items_bought <- count(bg3, c("Source","Target")) # Trying to find interesting items which were bought multiple times.
# We need items which are sold and bought more than 7 times by the same people.

max(items_sold$freq)
min(items_sold$freq)
max(items_bought$freq)
min(items_bought$freq)
unique(items_sold$freq)

items_sold <- items_sold %>% filter(items_sold$freq >= 7)
items_bought <- items_bought %>% filter(items_bought$freq >= 7)

#items_sold$Source[items_sold$Target==643087]

```

```{r}
## Items which are both sold and bought more than 7 times:
frequent_items<-intersect(items_sold$Target, items_bought$Target)
```








```{r}
## Extracting the rows for which Targets belong to the list of common items which were both sold and bought:
# Don't run
for (i in bg23$Target) {
  for (j in frequent_items) {
    if(i==j){
      trans <- rbind(bg23[bg23$Target==j])
    } 
    
  }
  
}
trans
nrow(trans)


```


```{r}
for (i in bg23$Target) {
  if(i==525263){
    trans <- bg23[bg23$Target==525263]
  }
  
}
trans
```





```{r}
ggplot(trans, aes(x=as.character(Source), y=Time, color = as.character(eType), fill=as.character(eType))) + 
  geom_point(shape=23, size = 5)+theme(axis.text.x=element_text(size=10, angle=90))+labs(title="Source Target Combinations for Big Graph ",
                                    x="Source & Target Combination", y = "Time")
```

```{r}
# Sources which are similar to template.
# 487668:S:644830,585212
# 482264:S:595104,570284
# 657187:S:550287,512397
```

643087 589127 483999 520837 583906 555931 595800 597727 606994 569215 641131 590595 547205 631478 490745 552748 596301
492039 469675 554011 597461 651537 544444 499177 614798 511389 461577 482579 654011 567511 605235 467222 649122 604359
592419 525263 588802 485885 563055 544415 578918 560703 473475 586881 466410 543037 657187 482264 487668


```{r}
trans <- bg23[bg23$Target==487668]
ggplot(trans, aes(x=as.character(Source), y=Time, color = as.character(eType), fill=as.character(eType))) + 
  geom_point(shape=23, size = 5)+theme(axis.text.x=element_text(size=10, angle=90))+labs(title="Source Target Combinations for Big Graph ",
                                    x="Source & Target Combination", y = "Time")
```

```{r}
trans <- bg23[bg23$Target==482264]
ggplot(trans, aes(x=as.character(Source), y=Time, color = as.character(eType), fill=as.character(eType))) + 
  geom_point(shape=23, size = 5)+theme(axis.text.x=element_text(size=10, angle=90))+labs(title="Source Target Combinations for Big Graph ",
                                    x="Source & Target Combination", y = "Time")
```

```{r}
trans <- bg23[bg23$Target==657187]
ggplot(trans, aes(x=as.character(Source), y=Time, color = as.character(eType), fill=as.character(eType))) + 
  geom_point(shape=23, size = 5)+theme(axis.text.x=element_text(size=10, angle=90))+labs(title="Source Target Combinations for Big Graph ",
                                    x="Source & Target Combination", y = "Time")
```

```{r}
trans <- bg23[bg23$Target==567511]
ggplot(trans, aes(x=as.character(Source), y=Time, color = as.character(eType), fill=as.character(eType))) + 
  geom_point(shape=23, size = 5)+theme(axis.text.x=element_text(size=10, angle=90))+labs(title="Source Target Combinations for Big Graph ",
                                    x="Source & Target Combination", y = "Time")
```

## Travel Channel:

```{r}
# Load The Data:
bg6 <- data.table::fread(here::here("data", "BigGraphData", "eType6.csv"))

nrow(bg6)

head(bg6)
tail(bg6)
length(unique(bg6$Target))
length(unique(bg6$Source))
```


```{r}
colnames(bg6)
bg6 <- subset(bg6, select = -c(SourceLatitude, TargetLatitude, SourceLongitude, TargetLongitude))

bg6 <- bg6[!duplicated(bg6)]
nrow(bg6)
#bg6$Time <- floor(bg6$Time/(3600*7*24))
```

## Find the Locations visited at the same time:

```{r}
location_clusters <- count(bg6, c("Time"))
nrow(location_clusters)
min(location_clusters$freq)
max(location_clusters$freq)
unique(location_clusters$freq)
location_clusters <- location_clusters %>% filter(location_clusters$freq >2 )
#length(unique(location_clusters$Time))
#time <- unique(location_clusters$Time)
location_clusters$Source[location_clusters$freq==28] #643925
length(unique(location_clusters$Source))


```


```{r}
#target1 <- bg6[bg6$Time == 5961600 & bg6$Target == 499467 & bg6$SourceLocation ==0]
#target2 <- bg6[bg6$Time == 7084800 & bg6$Target == 616453 & bg6$SourceLocation ==1]
target3 <- bg6[bg6$Time == 259200 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target4 <- bg6[bg6$Time == 950400 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target5 <- bg6[bg6$Time == 4752000 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target6 <- bg6[bg6$Time == 5961600 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target7 <- bg6[bg6$Time == 14860800 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target8 <- bg6[bg6$Time == 23587200 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target9 <- bg6[bg6$Time == 24624000 & bg6$Target == 499467 & bg6$SourceLocation ==0]
target10 <- bg6[bg6$Time == 30931200 & bg6$Target == 499467 & bg6$SourceLocation ==0]

target11 <- bg6[bg6$Time == 4752000 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target12 <- bg6[bg6$Time == 6134400 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target13 <- bg6[bg6$Time == 7689600 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target14 <- bg6[bg6$Time == 9936000 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target15 <- bg6[bg6$Time == 12700800 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target16 <- bg6[bg6$Time == 15811200 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target17 <- bg6[bg6$Time == 19353600 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target18 <- bg6[bg6$Time == 30137947 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target19 <- bg6[bg6$Time == 19353600 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target20 <- bg6[bg6$Time == 19353600 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target21 <- bg6[bg6$Time == 19353600 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target22 <- bg6[bg6$Time == 19353600 & bg6$Target == 616453 & bg6$SourceLocation ==0]
target23 <- bg6[bg6$Time == 19353600 & bg6$Target == 616453 & bg6$SourceLocation ==0]

target24 <- bg6[bg6$Time == 3801600 & bg6$Target == 625756 & bg6$SourceLocation ==0]
target25 <- bg6[bg6$Time == 6825600 & bg6$Target == 625756 & bg6$SourceLocation ==0]
target26 <- bg6[bg6$Time == 15811200 & bg6$Target == 625756 & bg6$SourceLocation ==0]
target27 <- bg6[bg6$Time == 26352000 & bg6$Target == 625756 & bg6$SourceLocation ==0]

target28 <- bg6[bg6$Time == 5443200 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target29 <- bg6[bg6$Time == 7603200 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target30 <- bg6[bg6$Time == 8380800 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target31 <- bg6[bg6$Time == 9244800 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target32 <- bg6[bg6$Time == 9763200 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target33 <- bg6[bg6$Time == 10540800 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target34 <- bg6[bg6$Time == 17798400 & bg6$Target == 657173 & bg6$SourceLocation ==0]
target35 <- bg6[bg6$Time == 21772800 & bg6$Target == 657173 & bg6$SourceLocation ==0]

target36 <- bg6[bg6$Time == 16871206 & bg6$Target == 499467 & bg6$SourceLocation ==1]

target37 <- bg6[bg6$Time == 29030400 & bg6$Target == 509607 & bg6$SourceLocation ==1]

target38 <- bg6[bg6$Time == 7084800 & bg6$Target == 616453 & bg6$SourceLocation ==1]

target39 <- bg6[bg6$Time == 17971200 & bg6$Target == 625756 & bg6$SourceLocation ==1]
target40 <- bg6[bg6$Time == 31017600 & bg6$Target == 625756 & bg6$SourceLocation ==1]

#target41 <- bg6[bg6$Time == 16093606 & bg6$Target == 509607 & bg6$SourceLocation ==2]

target42 <- bg6[bg6$Time == 16093606 & bg6$Target == 561157 & bg6$SourceLocation ==2]

target43 <- bg6[bg6$Time == 259200 & bg6$Target == 616453 & bg6$SourceLocation ==2]
target44 <- bg6[bg6$Time == 24105600 & bg6$Target == 616453 & bg6$SourceLocation ==2]

target45 <- bg6[bg6$Time == 24796800 & bg6$Target == 499467 & bg6$SourceLocation ==3]

target46 <- bg6[bg6$Time == 19180800 & bg6$Target == 561157 & bg6$SourceLocation ==3]
target47 <- bg6[bg6$Time == 30224347 & bg6$Target == 561157 & bg6$SourceLocation ==3]

target48 <- bg6[bg6$Time == 7084800 & bg6$Target == 616453 & bg6$SourceLocation ==3]
target49 <- bg6[bg6$Time == 11750400 & bg6$Target == 616453 & bg6$SourceLocation ==3]
target50 <- bg6[bg6$Time == 13824000 & bg6$Target == 616453 & bg6$SourceLocation ==3]
target51 <- bg6[bg6$Time == 19440000 & bg6$Target == 616453 & bg6$SourceLocation ==3]

target52 <- bg6[bg6$Time == 13132800 & bg6$Target == 625756 & bg6$SourceLocation ==5]
target53 <- bg6[bg6$Time == 30412800 & bg6$Target == 625756 & bg6$SourceLocation ==5]



target499467 <- rbind(target3,target4,target5,target6,target7,target8,target9,target10,target36,target45)
target509607 <- rbind(target37)
target561157 <- rbind(target42,target46,target47)
target616453 <- rbind(target48,target49,target50,target51, target44, target43, target38, target11,target12,target13,target14,target15,target16,target17,target18,target19,target20,target21,target22,target23)
target625756 <- rbind(target52,target53,target39,target40,target24,target25,target26,target27)
target657173 <- rbind(target28,target29,target30,target31,target32,target33,target34,target35)


```

```{r}
target499467 <- target499467 %>% filter(Weight != -1)
target509607 <- target509607 %>% filter(Weight != -1)
target561157 <- target561157 %>% filter(Weight != -1)
target616453 <- target616453 %>% filter(Weight != -1)
target625756 <- target625756 %>% filter(Weight != -1)
target657173 <- target657173 %>% filter(Weight != -1)


target499467 <- target499467[order(target499467$Time),]

```



```{r fig.width=10, fig.height=10, echo=FALSE}
ggplot(target499467, aes(x=(Time/86400), y=as.character(Source), color = as.character(SourceLocation),fill=as.character(SourceLocation))) + 
  geom_point(shape=23, size = 5)+labs(title="Travel Channel Analysis for target499467",
                                    x="Time", y = "Source")
```

```{r fig.width=10, fig.height=10, echo=FALSE}
ggplot(target509607, aes(x=(Time/86400), y=as.character(Source), color = as.character(SourceLocation),fill=as.character(SourceLocation))) + 
  geom_point(shape=23, size = 5)+labs(title="Travel Channel Analysis for target509607",
                                    x="Time", y = "Source")
```


```{r fig.width=10, fig.height=10, echo=FALSE}
ggplot(target561157, aes(x=(Time/86400), y=as.character(Source), color = as.character(SourceLocation),fill=as.character(SourceLocation))) + 
  geom_point(shape=23, size = 5)+labs(title="Travel Channel Analysis for target561157",
                                    x="Time", y = "Source")
```


```{r fig.width=10, fig.height=15, echo=FALSE}
ggplot(target616453, aes(x=(Time/86400), y=as.character(Source), color = as.character(SourceLocation),fill=as.character(SourceLocation))) + 
  geom_point(shape=23, size = 5)+labs(title="Travel Channel Analysis for target616453",
                                    x="Time", y = "Source")
```


```{r fig.width=10, fig.height=10, echo=FALSE}
ggplot(target625756, aes(x=(Time/86400), y=as.character(Source), color = as.character(SourceLocation),fill=as.character(SourceLocation))) + 
  geom_point(shape=23, size = 5)+labs(title="Travel Channel Analysis for target625756",
                                    x="Time", y = "Source")
```

```{r fig.width=10, fig.height=10, echo=FALSE}
ggplot(target657173, aes(x=(Time/86400), y=as.character(Source), color = as.character(SourceLocation),fill=as.character(SourceLocation))) + 
  geom_point(shape=23, size = 5)+labs(title="Travel Channel Analysis for target657173",
                                    x="Time", y = "Source")
```

## Crosschecking for Travel nodes found from Procurement seeds:

```{r}

list1 <- unique(target499467$Source)
list2 <- unique(target616453$Source)
list3 <- unique(target625756$Source)
list4 <- unique(target657173$Source)

list_proc1 <- c(475195, 574889, 518314, 550474, 569775, 498027, 501111, 583598, 505404, 643353, 512759, 491352, 613772, 477102, 569998, 461129, 579110, 492212, 469138, 572724, 514271, 638684, 482646, 611846, 535029, 463277, 561612, 604870, 595190, 496486, 645755, 496041, 592770, 585212, 522187, 544085, 565019, 644179, 586365, 601268, 529049, 535347, 574525, 464175, 477422, 491923, 579271, 570859, 522181, 595111, 615069, 646548, 492936, 538340, 513299, 465345, 570939, 532750, 468754, 550645, 618814, 573603, 535478, 507656, 538540, 465111, 607160, 507330, 560899, 618893, 457634, 582592, 502823, 624755, 518223, 633472, 607147, 597418, 531158, 606484, 477306, 480366, 635458, 465373, 561603, 567214, 528352, 612840, 558922, 578601, 535275, 636142, 480557, 513918, 560455, 603824, 606698, 523968, 509364, 626959, 599441, 534034)

list_proc2 <- c(570284, 649553)

list_proc3 <- c(500689, 509466, 459410, 638428, 519289, 630545, 564912, 566000, 609304, 486533, 539551, 513204, 470807, 652079, 607756, 534852, 643821, 492650, 485001, 634621, 514045, 655945, 510449, 569620, 626591, 647251, 557013, 505446, 497906, 512397, 502225, 470791, 498879, 648815, 469237, 479236, 646479, 483323, 478392, 474818, 527185, 548351, 463456, 503230, 554397, 605306, 534042, 528686, 570602, 527265, 460996, 579787, 586529, 547317, 480308, 527332, 458436, 636720, 611501, 551679, 630500, 574628, 580068, 643483, 624073, 480719, 487178, 515591, 631859, 479353, 586699, 464209, 617795, 536694, 586516, 603252, 631687, 547675, 475315, 482753, 478391, 569432, 460253, 477536, 599782, 611672, 585598, 512514, 518941, 609759, 528717, 459958, 587480, 650501, 543244, 624653, 517986, 526237, 519553, 601986, 466421, 508149, 614696, 639136, 456884, 654781, 531614, 594333, 554123, 494766, 498877, 508376, 556324, 579679, 546921, 532535, 523979, 643257, 506114, 524335, 644424, 501007, 618183, 538036, 586533, 518912, 587997, 598028, 536442, 490740, 461451, 654134, 511663, 501927, 650110, 517616, 486422, 609211, 637139, 565347, 547941, 613939, 561932, 566342, 610904, 592149, 526085, 517179, 498805, 533211, 626428, 502811, 650294, 488511, 621675, 527785, 580781, 635635, 535121, 508620, 655538, 567922, 575919, 522040, 628063, 571544, 588296, 641805, 558325, 505510, 644765, 568148, 609573, 650493, 649495, 559072, 573621, 558312, 594061, 621289, 510310, 572641, 641141, 461642, 605446, 502342, 641650, 633703, 535616, 543728, 479587, 476714, 559115, 562347, 544580, 550298, 629383, 460810, 598500, 656354, 529119, 517503, 504489, 645851, 529736, 510110, 653085, 581536, 619831, 482032, 539902, 600337, 517801, 604269, 593261, 580710, 645374, 458201, 633185, 573548, 539809, 579556, 607219, 636645, 590197, 470809, 542533, 479692, 537927, 525876, 514928, 467492, 614311, 492254, 527775, 549241, 574174, 495748, 459039, 641540, 614812, 636210, 638636, 525534, 558892, 570590, 516414, 507020, 484728, 598029, 603799, 651813, 585845, 605764, 488019, 657628, 611942, 557039, 551134, 577754, 624650, 657353, 582427, 459937, 575240, 575348, 546613, 501800, 625938, 464335, 537793, 477441, 498086, 592267, 487340, 510299, 582514, 615183, 561784, 637255, 513819, 493482, 461710, 654007, 498242, 567482, 575906, 553821, 534688, 483423, 480763, 648555, 534689, 482583, 516296, 516920, 500499, 553714, 495038, 506620)
```

```{r}
for (source in c(list1,list2,list3, list4)) {
  for (source2 in list_proc3) {
    if(source == source2){
      print(source)
    }
    
  }
  
}
## Sources found for procurement1: 534034, 592770
## Sources found for procurement3: 598500

```

```{r}
comm_proc1 <- data.table::fread(here::here("dataQ3", "ProcSeed1-GraphCom.csv"))
comm_proc2 <- data.table::fread(here::here("dataQ3", "ProcSeed2-GraphCom.csv"))
comm_proc3 <- data.table::fread(here::here("dataQ3", "ProcSeed3-GraphCom.csv"))


list_comm1 <- c(unique(comm_proc1$Source), unique(comm_proc1$Target))
list_comm2 <- c(unique(comm_proc2$Source), unique(comm_proc2$Target))
list_comm3 <- c(unique(comm_proc3$Source), unique(comm_proc3$Target))
```

```{r}
for (source in c(list1,list2,list3, list4)) {
  for (source2 in list_comm3) {
    if(source == source2){
      print(source)
    }
    
  }
  
}

# from List comm 1: 534034
```


## Clustering:

```{r}
library(klaR)
colnames(bg6)
clusters <- kmodes(bg6[,c(3,4,6)],6,iter.max = 10, weighted = FALSE)
output <- cbind(bg6,clusters$cluster)
colnames(output)[which(names(output) == "V2")] <- "cluster"
output
```

```{r}
plot(bg6[,c(3,4,6)],col= output$cluster)
```




