---
title: "Measure_Analysis"
output: html_document
---

```{r setup, include=FALSE}
library(igraph)
library(here)
library(tidyverse)
library (readr)
library (haven)
library (ggplot2)
library(transport)
```

## Pre-Processing the Data:

```{r cars}
# Load The Data:
dt <- data.table::fread(here::here("data", "CGCS-Template.csv"))
qt1 <- data.table::fread(here::here("data", "Q1-Graph1.csv"))
qt2 <- data.table::fread(here::here("data", "Q1-Graph2.csv"))
qt3 <- data.table::fread(here::here("data", "Q1-Graph3.csv"))
qt4 <- data.table::fread(here::here("data", "Q1-Graph4.csv"))
qt5 <- data.table::fread(here::here("data", "Q1-Graph5.csv"))
s1 <- data.table::fread(here::here("dataQ2","dfSeed1Reduced.csv"))
s3 <- data.table::fread(here::here("dataQ2","dfSeed3Reduced.csv"))
proc_s1_full <- data.table::fread(here::here("dataQ3","FinalGraphs2", "dfProcSeed1-Graph2ReducedFinal.csv"))
proc_s3_full <- data.table::fread(here::here("dataQ3","FinalGraphs2", "dfProcSeed3-Graph2ReducedFinal.csv"))

dt_network <- subset(dt, select = c(Source, Target, Weight))
qt1_network <- subset(qt1, select = c(Source, Target, Weight))
qt2_network <- subset(qt2, select = c(Source, Target, Weight))
qt3_network <- subset(qt3, select = c(Source, Target, Weight))
qt4_network <- subset(qt4, select = c(Source, Target, Weight))
qt5_network <- subset(qt5, select = c(Source, Target, Weight))
s1_network <- subset(s1, select = c(Source, Target, Weight))
s3_network <- subset(s3, select = c(Source, Target, Weight))
proc_s1_full_network <- subset(proc_s1_full, select = c(Source, Target, Weight))
proc_s3_full_network <- subset(proc_s3_full, select = c(Source, Target, Weight))

dt_edgelist <- dt_network
dt_graph <- graph.data.frame(dt_edgelist, directed = TRUE)

qt1_edgelist <- qt1_network
qt1_graph <- graph.data.frame(qt1_edgelist, directed = TRUE)

qt2_edgelist <- qt2_network
qt2_graph <- graph.data.frame(qt2_edgelist, directed = TRUE)

qt3_edgelist <- qt3_network
qt3_graph <- graph.data.frame(qt3_edgelist, directed = TRUE)

qt4_edgelist <- qt4_network
qt4_graph <- graph.data.frame(qt4_edgelist, directed = TRUE)

qt5_edgelist <- qt5_network
qt5_graph <- graph.data.frame(qt5_edgelist, directed = TRUE)

s1_edgelist <- s1_network
s1_graph <- graph.data.frame(s1_edgelist, directed = TRUE)

s3_edgelist <- s3_network
s3_graph <- graph.data.frame(s3_edgelist, directed = TRUE)

proc_s1_full_edgelist <- proc_s1_full_network
proc_s1_full_graph <- graph.data.frame(proc_s1_full_edgelist, directed = TRUE)

proc_s3_full_edgelist <- proc_s3_full_network
proc_s3_full_graph <- graph.data.frame(proc_s3_full_edgelist, directed = TRUE)


```


```{r}
#Import the sample_attributes
Template_Attributes<-data.table::fread(here::here("data", "CGCS-Template-NodeTypes.csv"))
Graph_Attributes<-data.table::fread(here::here("data", "CGCS-GraphData-NodeTypes.csv"))

#NodeType	Description
#  1	      Person
#  2	  Product category
#  3	      Document
#  4	  Financial category
#  5	      Country
c_person <- "blue"
c_item <- "red"
c_country <- "green"
c_rest <- "yellow"

c_eType01 <- "black"
c_eType23 <- "orange"
c_eType6 <- "cyan"
c_eType45 <- "magenta"

```


## Out-Degree:

```{r pressure, echo=FALSE}

## Template:
dt_graph2<-igraph::simplify(dt_graph, remove.multiple = FALSE, remove.loops = FALSE)
qt1_graph2<-igraph::simplify(qt1_graph, remove.multiple = FALSE, remove.loops = FALSE)
qt2_graph2<-igraph::simplify(qt2_graph, remove.multiple = FALSE, remove.loops = FALSE)
qt3_graph2<-igraph::simplify(qt3_graph, remove.multiple = FALSE, remove.loops = FALSE)
qt4_graph2<-igraph::simplify(qt4_graph, remove.multiple = FALSE, remove.loops = FALSE)
qt5_graph2<-igraph::simplify(qt5_graph, remove.multiple = FALSE, remove.loops = FALSE)
s1_graph2<-igraph::simplify(s1_graph, remove.multiple = FALSE, remove.loops = FALSE)
s3_graph2<-igraph::simplify(s3_graph, remove.multiple = FALSE, remove.loops = FALSE)
proc_s1_full_graph2<-igraph::simplify(proc_s1_full_graph, remove.multiple = FALSE, remove.loops = FALSE)
proc_s3_full_graph2<-igraph::simplify(proc_s3_full_graph, remove.multiple = FALSE, remove.loops = FALSE)
#Layout Options
set.seed(3952)  # set seed to make the layout reproducible
layout1 <- layout.fruchterman.reingold(dt_graph2, niter=5000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(dt_graph2)$color <- "grey"
V(dt_graph2)[degree(dt_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(dt_graph2)$size=(degree(dt_graph, mode = "out")+50)/3 #because we have wide range, I am dividing by 5 to keep the high in-degree nodes from overshadowing everything else.

V(dt_graph2)$color <- ifelse(Template_Attributes[V(dt_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(dt_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(dt_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(dt_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(dt_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

## Graph1:
layout1 <- layout.fruchterman.reingold(qt1_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt1_graph2)$color <- "grey"
V(qt1_graph2)[degree(qt1_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt1_graph2)$size=(degree(qt1_graph, mode = "out")+50)/3


V(qt1_graph2)$color <- ifelse(Template_Attributes[V(qt1_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt1_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt1_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt1_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt1_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

## Graph2:
layout1 <- layout.fruchterman.reingold(qt2_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt2_graph2)$color <- "grey"
V(qt2_graph2)[degree(qt2_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt2_graph2)$size=(degree(qt2_graph, mode = "out")+50)/3


V(qt2_graph2)$color <- ifelse(Template_Attributes[V(qt2_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt2_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt2_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt2_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt2_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph3:
layout1 <- layout.fruchterman.reingold(qt3_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt3_graph2)$color <- "grey"
V(qt3_graph2)[degree(qt3_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt3_graph2)$size=(degree(qt3_graph, mode = "out")+50)/3


V(qt3_graph2)$color <- ifelse(Template_Attributes[V(qt3_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt3_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt3_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt3_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt3_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph4:
layout1 <- layout.fruchterman.reingold(qt4_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt4_graph2)$color <- "grey"
V(qt4_graph2)[degree(qt4_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt4_graph2)$size=(degree(qt4_graph, mode = "out")+50)/3


V(qt4_graph2)$color <- ifelse(Template_Attributes[V(qt4_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt4_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt4_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt4_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt4_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph5:
layout1 <- layout.fruchterman.reingold(qt5_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt5_graph2)$color <- "grey"
V(qt5_graph2)[degree(qt5_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt5_graph2)$size=(degree(qt5_graph, mode = "out")+50)/3


V(qt5_graph2)$color <- ifelse(Template_Attributes[V(qt5_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt5_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt5_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt5_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt5_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Seed1:
layout1 <- layout.fruchterman.reingold(s1_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(s1_graph2)$color <- "grey"
V(s1_graph2)[degree(s1_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(s1_graph2)$size=(degree(s1_graph, mode = "out")+50)/3


V(s1_graph2)$color <- ifelse(Template_Attributes[V(s1_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(s1_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(s1_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(s1_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(s1_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Seed3:
layout1 <- layout.fruchterman.reingold(s3_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(s3_graph2)$color <- "grey"
V(s3_graph2)[degree(s3_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(s3_graph2)$size=(degree(s3_graph, mode = "out")+50)/3


V(s3_graph2)$color <- ifelse(Template_Attributes[V(s3_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(s3_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(s3_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(s3_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(s3_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Proc Seed1:
layout1 <- layout.fruchterman.reingold(proc_s1_full_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(proc_s1_full_graph2)$color <- "grey"
V(proc_s1_full_graph2)[degree(proc_s1_full_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(proc_s1_full_graph2)$size=(degree(proc_s1_full_graph, mode = "out")+50)/3


V(proc_s1_full_graph2)$color <- ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(proc_s1_full_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(proc_s1_full_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Proc Seed3:
layout1 <- layout.fruchterman.reingold(proc_s3_full_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(proc_s3_full_graph2)$color <- "grey"
V(proc_s3_full_graph2)[degree(proc_s3_full_graph, mode="out")>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(proc_s3_full_graph2)$size=(degree(proc_s3_full_graph, mode = "out")+50)/3


V(proc_s3_full_graph2)$color <- ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(proc_s3_full_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(proc_s3_full_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

```

## Betweenness:

```{r}
## Template:

dt_graph2<-igraph::simplify(dt_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt1_graph2<-igraph::simplify(qt1_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt2_graph2<-igraph::simplify(qt2_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt3_graph2<-igraph::simplify(qt3_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt4_graph2<-igraph::simplify(qt4_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt5_graph2<-igraph::simplify(qt5_graph, remove.multiple = TRUE, remove.loops = FALSE)
s1_graph2<-igraph::simplify(s1_graph, remove.multiple = TRUE, remove.loops = FALSE)
s3_graph2<-igraph::simplify(s3_graph, remove.multiple = TRUE, remove.loops = FALSE)
proc_s1_full_graph2<-igraph::simplify(proc_s1_full_graph, remove.multiple = TRUE, remove.loops = FALSE)
proc_s3_full_graph2<-igraph::simplify(proc_s3_full_graph, remove.multiple = TRUE, remove.loops = FALSE)

#Layout Options
set.seed(3952)  # set seed to make the layout reproducible
layout1 <- layout.fruchterman.reingold(dt_graph2, niter=5000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(dt_graph2)$color <- "grey"
V(dt_graph2)[betweenness(dt_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(dt_graph2)$size=(betweenness(dt_graph)+300)/20 #because we have wide range, I am dividing by 5 to keep the high in-degree nodes from overshadowing everything else.

V(dt_graph2)$color <- ifelse(Template_Attributes[V(dt_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(dt_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(dt_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(dt_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(dt_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

## Graph1:
layout1 <- layout.fruchterman.reingold(qt1_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt1_graph2)$color <- "grey"
V(qt1_graph2)[betweenness(qt1_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt1_graph2)$size=(betweenness(qt1_graph)+300)/20


V(qt1_graph2)$color <- ifelse(Template_Attributes[V(qt1_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt1_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt1_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt1_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt1_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

## Graph2:
layout1 <- layout.fruchterman.reingold(qt2_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt2_graph2)$color <- "grey"
V(qt2_graph2)[betweenness(qt2_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt2_graph2)$size=(betweenness(qt2_graph)+300)/20


V(qt2_graph2)$color <- ifelse(Template_Attributes[V(qt2_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt2_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt2_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt2_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt2_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph3:
layout1 <- layout.fruchterman.reingold(qt3_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt3_graph2)$color <- "grey"
V(qt3_graph2)[betweenness(qt3_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt3_graph2)$size=(betweenness(qt3_graph)+300)/20


V(qt3_graph2)$color <- ifelse(Template_Attributes[V(qt3_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt3_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt3_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt3_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt3_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph4:
layout1 <- layout.fruchterman.reingold(qt4_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt4_graph2)$color <- "grey"
V(qt4_graph2)[betweenness(qt4_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt4_graph2)$size=(betweenness(qt4_graph)+300)/20


V(qt4_graph2)$color <- ifelse(Template_Attributes[V(qt4_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt4_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt4_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt4_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt4_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph5:
layout1 <- layout.fruchterman.reingold(qt5_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(qt5_graph2)$color <- "grey"
V(qt5_graph2)[betweenness(qt5_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(qt5_graph2)$size=(betweenness(qt5_graph)+300)/20


V(qt5_graph2)$color <- ifelse(Template_Attributes[V(qt5_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt5_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt5_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt5_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt5_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Seed1:
layout1 <- layout.fruchterman.reingold(s1_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(s1_graph2)$color <- "grey"
V(s1_graph2)[betweenness(s1_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(s1_graph2)$size=(betweenness(s1_graph)+300)/20


V(s1_graph2)$color <- ifelse(Template_Attributes[V(s1_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(s1_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(s1_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(s1_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(s1_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Seed3:
layout1 <- layout.fruchterman.reingold(s3_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(s3_graph2)$color <- "grey"
V(s3_graph2)[betweenness(s3_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(s3_graph2)$size=(betweenness(s3_graph)+300)/20


V(s3_graph2)$color <- ifelse(Template_Attributes[V(s3_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(s3_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(s3_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(s3_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(s3_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Proc Seed1:
layout1 <- layout.fruchterman.reingold(proc_s1_full_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(proc_s1_full_graph2)$color <- "grey"
V(proc_s1_full_graph2)[betweenness(proc_s1_full_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(proc_s1_full_graph2)$size=(betweenness(proc_s1_full_graph)+300)/20


V(proc_s1_full_graph2)$color <- ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(proc_s1_full_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(proc_s1_full_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Proc Seed3:
layout1 <- layout.fruchterman.reingold(proc_s3_full_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

#Node or Vetex Options: Size and Color
V(proc_s3_full_graph2)$color <- "grey"
V(proc_s3_full_graph2)[betweenness(proc_s3_full_graph)>8]$color <- "yellow"  #Destinguishing High Degree Nodes as yellow
V(proc_s3_full_graph2)$size=(betweenness(proc_s3_full_graph)+300)/20


V(proc_s3_full_graph2)$color <- ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(proc_s3_full_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(proc_s3_full_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)
```

## Eigen Centrality:

```{r}

dt_graph2<-igraph::simplify(dt_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt1_graph2<-igraph::simplify(qt1_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt2_graph2<-igraph::simplify(qt2_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt3_graph2<-igraph::simplify(qt3_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt4_graph2<-igraph::simplify(qt4_graph, remove.multiple = TRUE, remove.loops = FALSE)
qt5_graph2<-igraph::simplify(qt5_graph, remove.multiple = TRUE, remove.loops = FALSE)
s1_graph2<-igraph::simplify(s1_graph, remove.multiple = TRUE, remove.loops = FALSE)
s3_graph2<-igraph::simplify(s3_graph, remove.multiple = TRUE, remove.loops = FALSE)
proc_s1_full_graph2<-igraph::simplify(proc_s1_full_graph, remove.multiple = TRUE, remove.loops = FALSE)
proc_s3_full_graph2<-igraph::simplify(proc_s3_full_graph, remove.multiple = TRUE, remove.loops = FALSE)

## Template:
#Layout Options
set.seed(3952)  # set seed to make the layout reproducible
layout1 <- layout.fruchterman.reingold(dt_graph2, niter=5000) #Creating a layout object to tell iGraph what layout I want

dt_vector <- eigen_centrality(dt_graph)$vector
dt_vector <- round(dt_vector)
#Node or Vetex Options: Size and Color
V(dt_graph2)$size<-(dt_vector+20)


V(dt_graph2)$color <- ifelse(Template_Attributes[V(dt_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(dt_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(dt_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(dt_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(dt_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

## Graph1:
layout1 <- layout.fruchterman.reingold(qt1_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

qt1_vector <- eigen_centrality(qt1_graph)$vector
qt1_vector <- round(qt1_vector)
#Node or Vetex Options: Size and Color
V(qt1_graph2)$size<-(qt1_vector+20)


V(qt1_graph2)$color <- ifelse(Template_Attributes[V(qt1_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt1_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt1_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt1_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt1_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)

## Graph2:
layout1 <- layout.fruchterman.reingold(qt2_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

qt2_vector <- eigen_centrality(qt2_graph)$vector
qt2_vector <- round(qt2_vector)
#Node or Vetex Options: Size and Color
V(qt2_graph2)$size<-(qt2_vector+20)



V(qt2_graph2)$color <- ifelse(Template_Attributes[V(qt2_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt2_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt2_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt2_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt2_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph3:
layout1 <- layout.fruchterman.reingold(qt3_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

qt3_vector <- eigen_centrality(qt3_graph)$vector
qt3_vector <- round(qt3_vector)
#Node or Vetex Options: Size and Color
V(qt3_graph2)$size<-(qt3_vector+20)



V(qt3_graph2)$color <- ifelse(Template_Attributes[V(qt3_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt3_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt3_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt3_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt3_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph4:
layout1 <- layout.fruchterman.reingold(qt4_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

qt4_vector <- eigen_centrality(qt4_graph)$vector
qt4_vector <- round(qt4_vector)
#Node or Vetex Options: Size and Color
V(qt4_graph2)$size<-(qt4_vector+20)



V(qt4_graph2)$color <- ifelse(Template_Attributes[V(qt4_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt4_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt4_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt4_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt4_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Graph5:
layout1 <- layout.fruchterman.reingold(qt5_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

qt5_vector <- eigen_centrality(qt5_graph)$vector
qt5_vector <- round(qt5_vector)
#Node or Vetex Options: Size and Color
V(qt5_graph2)$size<-(qt5_vector+20)



V(qt5_graph2)$color <- ifelse(Template_Attributes[V(qt5_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(qt5_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(qt5_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(qt5_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(qt5_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Seed1:
layout1 <- layout.fruchterman.reingold(s1_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

s1_vector <- eigen_centrality(s1_graph)$vector
s1_vector <- round(s1_vector)
#Node or Vetex Options: Size and Color
V(s1_graph2)$size<-(s1_vector+20)



V(s1_graph2)$color <- ifelse(Template_Attributes[V(s1_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(s1_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(s1_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(s1_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(s1_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Seed3:
layout1 <- layout.fruchterman.reingold(s3_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

s3_vector <- eigen_centrality(s3_graph)$vector
s3_vector <- round(s3_vector)
#Node or Vetex Options: Size and Color
V(s3_graph2)$size<-(s3_vector+20)


V(s3_graph2)$color <- ifelse(Template_Attributes[V(s3_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(s3_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(s3_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(s3_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(s3_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Proc Seed1:
layout1 <- layout.fruchterman.reingold(proc_s1_full_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

proc_s1_full_vector <- eigen_centrality(proc_s1_full_graph)$vector
proc_s1_full_vector <- round(proc_s1_full_vector)
#Node or Vetex Options: Size and Color
V(proc_s1_full_graph2)$size<-(proc_s1_full_vector+20)


V(proc_s1_full_graph2)$color <- ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(proc_s1_full_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(proc_s1_full_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(proc_s1_full_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)


## Proc Seed3:
layout1 <- layout.fruchterman.reingold(proc_s3_full_graph2, niter=1000) #Creating a layout object to tell iGraph what layout I want

proc_s3_full_vector <- eigen_centrality(proc_s3_full_graph)$vector
proc_s3_full_vector <- round(proc_s3_full_vector)
#Node or Vetex Options: Size and Color
V(proc_s3_full_graph2)$size<-(proc_s3_full_vector+20)


V(proc_s3_full_graph2)$color <- ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 1, c_person, 
                             ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 2, c_item,
                                    ifelse(Template_Attributes[V(proc_s3_full_graph), 2] == 5, c_country, c_rest)))

#Edge Options: Color
E(proc_s3_full_graph2)$color <- "grey"

#Plotting, Now Specifying an arrow size and getting rid of arrow heads
#We are letting the color and the size of the node indicate the directed nature of the graph
plot(proc_s3_full_graph2, edge.arrow.size=0.25,edge.arrow.mode = "-", vertex.label = NA)
```



